name: Appreciation

on: 
    pull_request:
        types:
            - closed
        branches:
            - main
            - master

jobs:
    Appreciation:
        uses: prajwalraju/GitHubAppreciator/.github/workflows/GitHubAppreciator.yml@main
        
        # Pass all secrets
        secrets: inherit 
